version: "3.9"

services:
  db:
    image: postgres:17
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: pepa-linha-dark
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.adminer.loadbalancer.server.port=8080

      - traefik.http.routers.adminer-http.rule=Host(`adminer.${DOMAIN}`)
      - traefik.http.routers.adminer-http.entrypoints=http
      - traefik.http.routers.adminer-http.middlewares=https-redirect

      - traefik.http.routers.adminer-https.rule=Host(`adminer.${DOMAIN}`)
      - traefik.http.routers.adminer-https.entrypoints=https
      - traefik.http.routers.adminer-https.tls=true
      - traefik.http.routers.adminer-https.tls.certresolver=le

  prestart:
    image: "${DOCKER_IMAGE_BACKEND}:${TAG-latest}"
    build:
      context: ./backend
    command: bash scripts/prestart.sh
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    env_file:
      - .env

  backend:
    image: "${DOCKER_IMAGE_BACKEND}:${TAG-latest}"
    restart: always
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
      prestart:
        condition: service_completed_successfully
    networks:
      - traefik-public
      - default
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.backend.loadbalancer.server.port=8000

      - traefik.http.routers.backend-http.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.backend-http.entrypoints=http
      - traefik.http.routers.backend-http.middlewares=https-redirect

      - traefik.http.routers.backend-https.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.backend-https.entrypoints=https
      - traefik.http.routers.backend-https.tls=true
      - traefik.http.routers.backend-https.tls.certresolver=le

  frontend:
    image: "${DOCKER_IMAGE_FRONTEND}:${TAG-latest}"
    restart: always
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://api.${DOMAIN}
        NODE_ENV: production
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public

      - traefik.http.services.frontend.loadbalancer.server.port=80

      - traefik.http.routers.frontend-http.rule=Host(`dashboard.${DOMAIN}`)
      - traefik.http.routers.frontend-http.entrypoints=http
      - traefik.http.routers.frontend-http.middlewares=https-redirect

      - traefik.http.routers.frontend-https.rule=Host(`dashboard.${DOMAIN}`)
      - traefik.http.routers.frontend-https.entrypoints=https
      - traefik.http.routers.frontend-https.tls=true
      - traefik.http.routers.frontend-https.tls.certresolver=le

volumes:
  app-db-data:

networks:
  traefik-public:
    external: true
