// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type PrivateUserCreate = {
    telegram_id: number;
    username?: (string | null);
    full_name?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TelegramLoginData = {
    id: number;
    first_name: string;
    last_name?: (string | null);
    username?: (string | null);
    photo_url?: (string | null);
    auth_date: number;
    hash: string;
};

export type TelegramWebAppData = {
    init_data: string;
};

export type UserCreate = {
    telegram_id: number;
    username?: (string | null);
    full_name?: (string | null);
    photo_url?: (string | null);
};

export type UserPublic = {
    telegram_id: number;
    username?: (string | null);
    full_name?: (string | null);
    photo_url?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    id: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    username?: (string | null);
    full_name?: (string | null);
    photo_url?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginWithTelegramData = {
    requestBody: TelegramLoginData;
};

export type LoginWithTelegramResponse = (Token);

export type LoginWithWebAppData = {
    requestBody: TelegramWebAppData;
};

export type LoginWithWebAppResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginGetTelegramConfigResponse = {
    bot_username: string;
};

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);